name: Modify README before merging pull requests

on:
  pull_request:
    types:
      - closed

permissions: write-all

jobs:
  modify-readme:
    if : github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Modify README
      run: |
        echo "MODIFIED" >> README.md

    - name: Commit changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -a -m "Modify README.md"
        git push
