name: Lock abbrlink

on:
  push:
    branches:
      - main

jobs:
  lock-abbrlink:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check if there are changes
      id: diff
      run: git diff --quiet
      continue-on-error: true

    - name: Commit changes
      if: ${{ steps.diff.outcome == 'failure' }}
      run: |
        git config user.name "GitHub Actions"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git commit -a -m "Lock abbrlink after #${{ github.event.after }}"
        git push
