name: Modify README before merging pull requests

on:
  pull_request:
    types: [opened, synchronize] # repoened???

jobs:
  modify-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Modify README
      run: |
        echo "MODIFIED" >> README.md

    - name: Commit changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git commit -a -m "Modify README.md"
        git push
