name: Modify README before merging pull requests

on:
  pull_request:
    types:
      - closed

jobs:
  modify-readme:
    if : github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Modify README
      run: |
        echo "MODIFIED" >> README.md

    - name: Commit changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git commit -a -m "Modify README.md"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.ref }}
